### PR TITLE
refactor: remove unnecessary code

### LINKED ISSUE #162: [08/03/2022]: Bad practice / Unused variables
There are multiple places that contain a bad practice of variable declarations or/and unused variables.

Consider the following example (server.js):

```javascript
/*
 Bad practice, since all "var" variables declared below are not being re-declared any further
 Also, "var" creates a global variable, making it available throughout the whole file using "this" keyword
*/
var i18next = require('i18next');
var FsBackend = require('i18next-fs-backend');
var middleware = require('i18next-http-middleware');

const { knex } = require('./util/db'); // unused variable

const MessagingResponse = require('twilio').twiml.MessagingResponse; // unused variable 
```

Files that have such problems:
- ```server.js```
- ```register-subscription.js```
- ```search-court-records.js```
- scripts
  - ```notify.js```
  - ```purge-and-update-subscription.js```
  - ```update_defendants.js```
- test 
  - ```app-court-search.test.js```
  - ```test-webhook.js```
- util 
  - ```twilio-actions.js``` 

The suggestion is to change ```var``` declaration to ```const``` (or ```let``` if the declared variable is being reassigned any further) and get rid of all unused variables.

### PR DESCRIPTION
**Pull request by Dun-sin**
---
name: "refactor: remove unnecessary code"
about: "I'm ready to check in some code to fix an issue!"
title: "2022-08-07: Remove unnecessary code"
assignee: Dun-sin
---

Closes #162 

**Please check if the PR fulfills these requirements**
- [x] The title contains the issue number if fulfills and a concise description of the changes
- [x] These changes are related to an open issue

**What changes are you introducing?**
- Changed variables that weren't reassigned from var to const
- removed variables and packages that weren't used

**Screenshots or Video**:

### CODE REVIEW

**Comment by ejaxon** [comment]
Hey, @Dun-sin, thanks for submitting this. I'm traveling at the moment and unable to look, so it may be a few days before I can review. Just wanted to give you a heads up. -Eric

**Comment by ejaxon** [comment]
Hi @Dun-sin, could you reformat to match the indents in the code base (2 spaces)? The addition of large indents makes it very hard to see exactly what has changed and creates a mis-match with the rest of the code.

Thanks,

Eric

**Comment by Dun-sin** [comment]
Sure will do that, but to make it pretty easy, so anyone doesn't alter style settings like this, it will be better to add a prettier file, maybe make an issue about it, up to you

**Comment by Dun-sin** [comment]
I really tried, but it's hard, the best way to fix this in every code is to add a prettier file

**Comment by ejaxon** [comment]
Hi @Dun-sin, I'm reopening because I want to make the corrections, though I probably won't just accept the request given the formatting issues. 

I'm hoping to finally get to all this this weekend - family issues have taken up all my spare time over the last few weeks. 

I think my preference is to start with ESLint rather than Prettier, but I agree with you that we should have an automated way fo at least flagging formatting errors. I will start working on that as soon as I can, unless you have any interest in doing so.

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, I'm reopening because I want to make the corrections, though I probably won't just accept the request given the formatting issues.
> 
> I'm hoping to finally get to all this this weekend - family issues have taken up all my spare time over the last few weeks.
> 
> I think my preference is to start with ESLint rather than Prettier, but I agree with you that we should have an automated way fo at least flagging formatting errors. I will start working on that as soon as I can, unless you have any interest in doing so.

You can mix ESLint and prettier, and yes, I can work on this. But once you run it, it's going to change every file to the right formatting

**Comment by ejaxon** [comment]
Ok, I'm a big fan of doing things one step at a time. I'm going to make the changes from your pull request since they are all going to be caught by a linter anyway. Then I'll set up ESLint with the AirBnB configuration and get the code clean according to that. Once that's done, we can add prettier (I assume there aren't huge formatting differences between prettier and AirBnB?).

**Comment by Dun-sin** [comment]
> Ok, I'm a big fan of doing things one step at a time. I'm going to make the changes from your pull request since they are all going to be caught by a linter anyway. Then I'll set up ESLint with the AirBnB configuration and get the code clean according to that. Once that's done, we can add prettier (I assume there aren't huge formatting differences between prettier and AirBnB?).

Prettier isn't exactly strict for styling like eslint, eslint just makes sure coding guidelines are followed I guess

**Comment by ejaxon** [comment]
@Dun-sin - I'm going to go ahead and close this. I made the substantive changes you had. I have also added the use of eslint using the AirBnB configuration on the server code and cleaned up all the linting errors there. I'm merging into development, but want to do a fair amount of testing before I push anything on to staging or production.

Once that's all through, we can take a look at maybe adding prettier as a next step.

**Pull request closed without merging**
