### PR TITLE
Shortened & fixed Russian translation on client/server

### LINKED ISSUE #166: [8/24/2022]: [Shorter/Fix Russian translation on client/server]
There are multiple occasions on the frontend where Russian translation text can be shortened.

### PR DESCRIPTION
**Pull request by GKosheev**
---
name: Shortened & Fixed Russian translation"
about: "I'm ready to check in some code to fix an issue!"
title: "[08/25/2022]: [Issue #166]"
assignee: colinalford
---

Closes #166 

**Please check if the PR fulfills these requirements**
- [x] The title contains the issue number if fulfills and a concise description of the changes
- [x] These changes are related to an open issue

On the server side, I've checked the ```en``` translations for ```reminder1``` and ```reminder2``` and found out that they are exactly the same, so I've changed the translation for the ```ru``` reminders as well.

### CODE REVIEW

**Review by ejaxon — CHANGES_REQUESTED** [review]
This is really helpful, @GKosheev! In reviewing I just found one place where I have a question. On line 5 of the server translation file, the new translation is: 
```
Ранее, вы отказались от отписались от получение сообщений с данного сайта. Для оформления подписки отправьте сообщение со словом START на {{phone}} и, затем, снова оформите подписку на сайте.

```
Shouldn't that be something like the following (I just deleted "отказались от" and changed the ending for receipt)?
```

Ранее, вы отписались от получения сообщений с данного сайта. Для оформления подписки отправьте сообщение со словом START на {{phone}} и, затем, снова оформите подписку на сайте.
```

When you fix that, you might also add a space between the period and "Рассмотрение" on line 12 (that was an existing mistake)

**Comment by GKosheev** [comment]
@ejaxon, Yes, you're right. I missed that while thinking about the word to shorter the sentence.
Fixed that and added a period at the place you mentioned.

**Review by ejaxon — COMMENTED** [review]
I'm going to approve and merge, but there's still a minor change. Should I change "получение" to "получения" on line 5 or just delete it. It makes sense to me either way (but my Russian obviously isn't native).

**Comment by ejaxon** [comment]
Went with the first, but just LMK and I'll drop the word and shorten further.

**Comment by GKosheev** [comment]
@ejaxon, yes, I missed that too :)
The correct version is "получения". I was looking for a way to make it shorter but didn't pay much attention to the spelling

**Pull request merged**
